### PR TITLE
pysingfel orientation/images in parallel (MPI)

### PR DESCRIPTION
**Pull request by marcgri**
psingfel parallelization

### CODE REVIEW

**Comment by marcgri** [comment]
major change to master-slave MPI model, master writes HDF5 file

**Comment by chuckie82** [comment]
Per our discussion:
1) Time 3x bcast vs 1x bcast
2) Time 2x send/recv vs 1x send/recv
3) argparse not used

**Comment by marcgri** [comment]
Hi Chuck,

I ran the timings for the broadcasting and send operations. Here is a quick summary.


  1.  The broadcasting 3x vs 1x did not differ by more than 5-`10%, Since the broadcast of the dictionary is simpler, I implemented that.
  2.  Reducing the sends in half decreased the time by 25%--so I updated the code to use the single send.
  3.  Argparse is now used, but I have only used the type of orientations and number of slices in the code so far.

Let me know if you have other comments, questions, or changes.

Best,

Marc

________________________________

**Comment by chuckie82** [comment]
Thanks for the timing information. Many send/recv operations become more costly as number of slaves goes up.

Code is much cleaner now.

**Pull request merged**
