### PR TITLE
Provisional fixes to radiationDamage scripts

### PR DESCRIPTION
**Pull request by apeck12**
These changes permitted running radiationDamageMPI using the sample pmi_out_0000001.h5 file supplied in #96. Here are example output diffraction patterns, with the particle rotated to a new random orientation for each:

download-1

Unresolved issues:
1. PlainDetector doesn’t correctly load the sample .geom files. It’s unclear to me whether the Epix/pnCCD files are unsuitable for this class, or if changes to the .geom format have made PlainDetector outdated. A SimpleSquareDetector is used as a placeholder. Depending on the detector type used, an additional line to assemble_image_stack may be needed.
2. Should detector_intensity be scaled by the Thomson factor as in the linear corrections from the Detector class? 
3. Code should be checked for successful execution when multiple .h5 files are available.
4. A positive detector distance seems to lead to correct results for the particle's scattering, but I'm not sure if it's correct for the Compton scattering as well. See issue #110.

### CODE REVIEW

**Comment by apeck12** [comment]
Hi @JunCEEE, thanks for the pmi_out test data file that you sent earlier. If you wouldn’t mind providing your tmp.geom geometry file and another .h5 file, I can try to fix the Detector class issue and check that the code runs when multiple data files are available.

**Comment by JunCEEE** [comment]
Hi @apeck12, I just got back from holiday. Sorry for this late reply. I've uploaded the files here: https://syncandshare.desy.de/index.php/s/m7byqzyZTMXB7pg

By the way, I guess that the patterns displayed above are from different sample orientations? Compton scattering indeed makes differences in diffraction patterns, but usually no such big difference.

**Comment by apeck12** [comment]
Thanks for sharing these files, @JunCEEE. The patterns above are from randomly oriented particles. Here’s the result when no rotations are applied to the sample:

download

In tmp.geom, what do the clen and res parameters correspond to? It looks like our Detector class has changed slightly, so the parameters in this file aren’t being read in at the moment. Also, are all distances in that file in meters?

**Comment by JunCEEE** [comment]
Hi @apeck12, the .geom file is in the [CrystFEL detector geometry description](https://www.desy.de/~twhite/crystfel/manual-crystfel_geometry.html) format. 

`clen` means "Camera Length". For each detector panel, `clen` is the distance between the sample and its projected image on the panel.
`res` means the resolution in pixels per meter. It's the reciprocal of the detector pixel size in meters.
All the distances are in meters in my understanding.

**Comment by apeck12** [comment]
Thanks for that information, @JunCEEE. The latest revisions fix the issue with the PlainDetector class, and the code terminates without error when multiple pmi_out files are available. Currently the max_adu and adu_per_photon parameters in the geometry file aren’t accounted for, so please let me know if that’s an issue or if you encounter any errors when running the code. 

@chuckie82, where would be the best place to find a multi-panel cheetah geometry file? I think the PlainDetector class may only work for a single panel as currently written. Alternatively, should multi-panel detectors fall under the scope of the more advanced detector classes?

Another potential issue I noticed is related to Compton scattering. When the the pmi_out file is loaded, the Particle class retrieves Compton data at specific values of q and estimates the Compton contribution at each detector pixel by interpolation. The max q of the available Compton data was less than the max q of the detector, and the Compton contribution was poorly estimated for pixels beyond this resolution. Below is a plot of resolution versus unadjusted Compton intensity for all detector pixels, with an inflection point where the Compton curve from the pmi_out file ends. 

download-1

Since the magnitude of the Compton contribution is small after adjusting for linear corrections, the intensity at these high resolution pixels is generally 0 after quantization. So I’m not sure if this needs to be addressed in the code.

**Comment by chuckie82** [comment]
@apeck12 what I gather from Mikhail is that we should use PSANA coordinate frame when we save psana geometry files. So if you look at the last line of a geometry file in pysingfel and the IP z-distance value is negative, that's probably a correct one to use.

**Comment by JunCEEE** [comment]
@apeck12 It's great. I will try the latest version by the end of this week. Thanks a lot.

**Comment by JunCEEE** [comment]
Hi @apeck12, when I tested your latest revisions (I hope this is the right one: 4cbcaaf0ebc5554c0d3e902c6a7f31641fc41f46) I got an error related to beam class initiallization.
My testing command: 
`mpirun -np $N_CPU radiationDamageMPI --inputDir /home/hydratedProject/w4_noW/pmi_out --outputDir $OUT_DIR  --geomFile tmp.geom --uniformRotation 1  --calculateCompton 1 --sliceInterval 100 --numSlices 100 --pmiStartID 1 --pmiEndID 12 --numDP 36`

My guess is that the current beam class cannot initialize when `beamfile = None`. In our case, the photon information is collected from the `pmi_out.h5` files, thus there is no beamfile needed. To have an `if beamfile == None` condition within which the `beam` class can be initialized with photon parameters from pmi_out files might be a solution.

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/pysingfel2/bin/radiationDamageMPI", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/pysingfel2/bin/radiationDamageMPI", line 6, in <module>
    main()
  File "/home/pysingfel2/pysingfel/radiationDamageMPI.py", line 26, in main
    slave_diffract(comm, parameters)
  File "/home/pysingfel2/pysingfel/radiationDamageMPI.py", line 108, in slave_diffract
    make_one_diffr(my_quaternion, counter, parameters, output_name)
  File "/home/pysingfel2/pysingfel/radiationDamage.py", line 108, in make_one_diffr
    beam = Beam(beamfile)
  File "/home/pysingfel2/pysingfel/beam/base.py", line 20, in __init__
    self.init_from_arg_dict(kwargs)
  File "/home/pysingfel2/pysingfel/beam/base.py", line 26, in init_from_arg_dict
    self.set_wave_parameters_from_arg_dict(arg_dict)
  File "/home/pysingfel2/pysingfel/beam/base.py", line 46, in set_wave_parameters_from_arg_dict
    raise TypeError("Beam needs a wavelength, "
TypeError: Beam needs a wavelength, photon_energy, or wavenumber.
```

**Comment by apeck12** [comment]
@JunCEEE, thanks for catching that error. I’ve updated the code to handle the case when no beam file is supplied. One thing I noticed is that pmi_out_0000002.h5 doesn’t contain beam parameters, so I assume these parameters are only guaranteed to be in the first file. Currently the code checks the current pmi file for these parameters, and then reverts to the first pmi file in the series (pmi_id=1) if it doesn’t find them. If a different set up would be preferred, please let me know.

I found that running the script on the two pmi_out files you provided, specifying 36 patterns per pmi file (--numDP 36) and no beam file yielded 72 simulated shots in the output diffr_out_0000001.h5 file. Here are a few sample patterns:

download

The figures shown earlier in this thread appear quite different because I increased the fluence for those. Please let me know if you encounter further bugs or expect a different output.

I also adjusted the way the Compton contribution is estimated for pixels at q-values beyond the range of the input data. A ‘mixed order’ approach is now used, in which cubic spline interpolation is used for in-range pixels and linear interpolation is used at q-values that require extrapolation. This seems to take care of the artifact described above.

download-2

**Comment by apeck12** [comment]
@chuckie82, @irischang020: to follow up on our discussion yesterday, these changes are designed to make coordinate conventions consistent across both non-LCLS and LCLS detectors. For LCLS detectors, the geometry file is now loaded using the psana coordinate frame by default. The file can alternatively be loaded using the lab coordinate frame by setting cframe=1. In both cases, a positive detector distance is enforced. For the Plain detector, the indexing scheme has been changed from Cartesian to matrix during initialization to match the SimpleSquare class.

Below is a comparison of patterns for a particle in the same orientation across different detectors using the default coordinate frame (cframe=0). For some detectors, only the central region is shown to aid visual comparison.

download-1

If the lab coordinate frame (cframe=1) is used instead, the results of the LCLS detector types are transposed compared to the the psana convention and the non-LCLS detectors:

download-2

**Comment by JunCEEE** [comment]
@apeck12 Many thanks for your update. I just tested the code. It worked well with the pmi_out_0000001.h5 file. But I just realized that the pmi_out_0000001.h5 is in a very early format, and the pmi_out_0000002.h5 is in the format we are currently using. That's why you didn't see the history group in the h5 file. I'm really sorry about the confusion caused. I've submitted a [PR](https://github.com/apeck12/pysingfel/pull/1) to your repository which should be able to support the newer format. I tested it on a GPU computing node at DESY without problems.

However, when I tested it on a CPU node, I got this error:
```
Traceback (most recent call last):
  File "/home/miniconda3/envs/pysingfel2/bin/radiationDamageMPI", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/pysingfel2/bin/radiationDamageMPI", line 6, in <module>
    main()
  File "/home/pysingfel2/pysingfel/radiationDamageMPI.py", line 24, in main
    master_diffract(comm, parameters)
  File "/home/pysingfel2/pysingfel/radiationDamageMPI.py", line 60, in master_diffract
    make_one_diffr(my_quaternion, ntask, parameters, output_name)
  File "/home/pysingfel2/pysingfel/radiationDamage.py", line 229, in make_one_diffr
    f_hkl_sq = det.get_pattern_without_corrections(particle)
  File "/home/pysingfel2/pysingfel/detector/base.py", line 181, in get_pattern_without_corrections
    import pysingfel.gpu.diffraction as pgd  # Only import GPU if needed
  File "/home/pysingfel2/pysingfel/gpu/__init__.py", line 1, in <module>
    from pysingfel.gpu.diffraction import *
  File "/home/pysingfel2/pysingfel/gpu/diffraction.py", line 10, in <module>
    def calculate_pattern_gpu_back_engine(form_factor, pixel_position, atom_position, pattern_cos,
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/decorators.py", line 100, in kernel_jit
    kernel.bind()
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/compiler.py", line 530, in bind
    self._func.get()
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/compiler.py", line 403, in get
    cuctx = get_context()
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 212, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 151, in _get_or_create_context_uncached
    with driver.get_active_context() as ac:
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 388, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/home/miniconda3/envs/pysingfel2/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 278, in __getattr__
    raise CudaSupportError("Error at driver init: \n%s:" %
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBA_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:
```
Does it support only GPU computing at this moment?

**Comment by chuckie82** [comment]
@JunCEEE we don't have plans to support CPUs. We feel it's too slow for any serious computation.

**Comment by apeck12** [comment]
@JunCEEE, thanks for the code to read the new pmi_out format and for fixing the legacy h5py calls as well. I’ve merged those PRs. I also amended the code so that it now only retrieves beam parameters from either a given beam file or the pmi_out file under consideration, rather than grabbing them from the first file in the series if parameters aren’t found.

@chuckie82, I think these commits resolve the issues with the radiationDamage scripts and different coordinate conventions between detector types and are ready to merge.

**Comment by JunCEEE** [comment]
@chuckie82 Yes, that's indeed a reasonable decision.

@apeck12 That's really nice. Thanks a lot.

**Pull request merged**
