### PR TITLE
Running example scripts in pytest

### PR DESCRIPTION
**Pull request by apeck12**
To follow up on issue #108 and PR #112, code has been added to check example scripts for successful termination (but not necessarily correctness). Running this in pytest takes a long time -- 15 minutes for the 8 examples -- compared to the other unit tests. Minor modifications were also made to the example scripts to enable running them from a different folder and to not take the absolute value of the detector distance, since a positive distance is now enforced in the LCLSDetector class.

Sorry, I thought this would be appended to PR #112 since I started working from the final commit in that series. The changes to pysingfel/detector/lcls.py, pysingfel/detector/plain.py, and pysingfel/experiment/base.py are already integrated into master but hadn't been committed to this branch.

### CODE REVIEW

**Comment by irischang020** [comment]
@apeck12 @chuckie82 To follow up on  Ariana's suggestion on Monday's meeting, do we add parameters (e.g. correction, shot noise)  into experiment/base.py, so that users can decide to turn on or off? (The default setting is including both, and the MPI script for generating large dataset is also using the SPIExperiment class.)

**Comment by apeck12** [comment]
Perhaps the following options would be useful for testing downstream reconstruction?
1) clean signal, using `detector.get_pattern_without_corrections`.
2) signal with corrections and quantization, using `detector.get_photons`.
3) signal with corrections and quantization, but with corrections reversed to recover the clean signal (but imperfectly due to quantization). This would rely on `detector.get_photons` followed by `detector.remove_polarization`; it looks like a `detector.remove_solid_angle` function would need to be added. We could also add an option to offset the estimated beam center from its ideal position to mimic the effect of calibration errors in removing polarization and solid angle effects. 

I’m not sure how useful a fourth option of clean signal + corrections would be if reconstruction assumes that solid angle and polarization effects have already been removed; in that case, we’d just want the clean signal (option 1). 

Down the line, do we also want SPI_MPI.py to accept any type of detector rather than be hardcoded for Pnccd?

**Comment by irischang020** [comment]
@apeck12 Could you try to create a new pull request? I couldn't git pull because of the conflicting files issue.

**Comment by irischang020** [comment]
> Down the line, do we also want SPI_MPI.py to accept any type of detector rather than be hardcoded for Pnccd?
The current MPI script is designed to accept any type of detector, as long as is it supported.
If the specific detector type is not supported, then we would see error from the line: pattern_shape = det.pedestals.shape.

**Comment by irischang020** [comment]
`detector.get_pattern_without_corrections`, `detector.get_photons` are calling `calculate_diffraction_pattern_gpu` and set the return type to 'intensity'. But actually `calculate_diffraction_pattern_gpu` can have two return types: 'intensity' or 'complex_field'. (compare with the functions in experiment/base.py).

The current MPI script is designed to accept any type of detector, as long as is it supported.
If the specific detector type is not supported, then we would see error from the line: pattern_shape = det.pedestals.shape.

**Comment by apeck12** [comment]
@irischang020, is [this](https://github.com/chuckie82/pysingfel/blob/master/examples/scripts/SPI_MPI.py) the current MPI script? Based on https://github.com/chuckie82/pysingfel/blob/6fe3923708e13a92a39187d546e8e026b25f8983/examples/scripts/SPI_MPI.py#L43 I assumed that other detector types weren't accepted, but please let me know if that’s not the case. Also, would it make sense to place this script and radiationDamageMPI.py in the same directory? Currently they’re in examples/scripts and pysingfel/pysingfel, respectively.

Thanks for pointing out the different return types for `calculate_diffraction_pattern_gpu`. I'm not sure that I understand what changes you're advising for the current output. For all types of simulated shots (clean signal +/- corrections and quantization), my impression is that the intensity should be returned by `calculate_diffraction_pattern_gpu`. It seems like the current set up of returning the complex_field for the full volume calculation will be useful to compare reference phases to those recovered by reconstruction. But it’s not clear to me how corrections / quantization could be applied if the simulated shots were complex-valued rather than the intensity field.

I'll finish creating the new PR once the CUDA issue is resolved -- sorry for the delay.

**Comment by irischang020** [comment]
@apeck12 
> @irischang020, is [this](https://github.com/chuckie82/pysingfel/blob/master/examples/scripts/SPI_MPI.py) the current MPI script? Based on
> 
> https://github.com/chuckie82/pysingfel/blob/6fe3923708e13a92a39187d546e8e026b25f8983/examples/scripts/SPI_MPI.py#L43

Yes, SPI_MPI.py is the MPI script, though I have another version for generating the large datasets we need for spinifel. I'll add the updated version after I create the next PR.
Right, we need to add a couple of lines for other detector types to be accepted:
e.g.
if PNCCD in geom:
    det = ps.PnccdDetector(geom=geom, beam=beam)
elif EPIX in geom:
    det = ps.Epix10kDetector(geom=geom, beam=beam)
else:
    det = ps.JungfrauDetector(geom=geom, beam=beam)
(need to figure out the exact substring for different geom)

> I assumed that other detector types weren't accepted, but please let me know if that’s not the case. Also, would it make sense to place this script and radiationDamageMPI.py in the same directory? Currently they’re in examples/scripts and pysingfel/pysingfel, respectively.

Perhaps we can move radiationDamage.py and  radiationDamageMPI.py to examples/scripts, so that all example scripts are placed in the same directory.

> Thanks for pointing out the different return types for `calculate_diffraction_pattern_gpu`. I'm not sure that I understand what changes you're advising for the current output. For all types of simulated shots (clean signal +/- corrections and quantization), my impression is that the intensity should be returned by `calculate_diffraction_pattern_gpu`. It seems like the current set up of returning the complex_field for the full volume calculation will be useful to compare reference phases to those recovered by reconstruction. But it’s not clear to me how corrections / quantization could be applied if the simulated shots were complex-valued rather than the intensity field.

generate_image_stack and _generate_group_complex_pattern in experiment/base.py shows how to do this.

> I'll finish creating the new PR once the CUDA issue is resolved -- sorry for the delay.

No worries. Thanks!

**Comment by apeck12** [comment]
@irischang020, thanks for that clarification about the updated SPI_MPI.py script. As for the matter of intensity versus complex_field, when `_generate_group_complex_pattern` is called in experiment/base.py, I think that the intensities are still calculated (line 78) prior to applying corrections. I’m not sure if these corrections and quantization can be applied to the complex-valued return, since it's unclear to me if or how things like solid angle and polarization affect the phase portion of the information. 

I’m closing this so that I can create a new PR once CUDA is functional again. I’ll move the radiationDamage scripts to examples/scripts then as you’ve suggested.

**Pull request closed without merging**
